# Generated by Django 4.2 on 2024-01-07 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_name",
        ),
    ]
