# Generated by Django 4.2 on 2024-01-07 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_customuser_user_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
