# Generated by Django 4.2 on 2024-01-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=9)),
                ("tsp", models.CharField(max_length=1)),
                ("oap", models.CharField(max_length=1)),
                ("is_bank", models.BooleanField(default=False)),
                ("body", models.CharField(max_length=200)),
            ],
        ),
    ]
